out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  group: hc_gs
  project: ZINCe_GPS_1
dataset:
  format: PyG-ZINC-Spasm
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+NodeCountEnc
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: TypeDictEdge
  edge_encoder_num_types: 4
  edge_encoder_bn: False
ctenc_NodeCountEnc:
  raw_bn: False
  dim_ogct: 42
  dim_hid: 42
  dim_ct: 42
  n_layers: 2
  dropout: 0.0
  norm: batch_norm
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: GINE+Transformer  # CustomGatedGCN+Performer
  layers: 8
  n_heads: 4
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
  varied_width: True
  dim_initial: 92
  initial_depth: 2
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64 # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 2000
  scheduler: cosine_with_warmup
  num_warmup_epochs: 50
