out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: ZINC_MLPpe_1
  group: run_repeats
dataset:
  format: PyG-ZINC
  name: subset
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: TypeDictNode+RWSE
  node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: mlp_flat
  dim_pe: 28
  raw_norm_type: BatchNorm
  layers: 2
  norm: "batch_norm"
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
  enforce_param_budget: true
  param_budget: 500000
model:
  type: MLPGraphReg
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
mlp:
  layers: 8
  dim_hidden: 156
  residual_connection: True
  batch_norm: False
  dropout: 0.1
  head: san_graph
optim:
  clip_grad_norm: False
#  optimizer: adamW
  optimizer: adam
  weight_decay: 1e-3
  base_lr: 0.001
  max_epoch: 1200
#  scheduler: custom_cosine_with_warmup
  sceduler: StepLR_with_warmup
  # sceduler: reduce_on_plateau
  # optim.reduce_factor: 0.5
  # cfg.optim.min_lr: .00001
  # optim.schedule_patience: 10
  # num_warmup_epochs: 10
