out_dir: results
metric_best: mae
metric_agg: argmin
seed: 0
wandb:
  use: True
  project: synth-MLP
  group: synth-MLP-RWSE
  entity: MoSE-experiments
dataset:
  format: EmJ-Synth
  name: FracDom
  task: graph
  task_type: regression
  transductive: False
  follow_edge_batch: True #set to true when processing edge features in parallel
  node_encoder: True
  node_encoder_name: TypeDictNode+RWSE
  node_encoder_num_types: 1
  node_encoder_bn: False
  edge_encoder: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: mlp_flat
  dim_pe: 63
  raw_norm_type: BatchNorm
  layers: 2
  norm: "batch_norm"
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: MLPGraphReg
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
mlp:
  layers: 4
  dim_hidden: 145
  residual_connection: True
  batch_norm: True
  dropout: 0.2
  head: san_graph
optim:
  clip_grad_norm: False
  optimizer: adam
  weight_decay: 0.0
  reduce_factor: 0.5
  schedule_patience: 10
  base_lr: 0.001
  max_epoch: 1000
  scheduler: StepLR_with_warmup
  num_warmup_epochs: 0