out_dir: results
metric_best: mae
metric_agg: argmin
seed: 0
wandb:
  use: True
  project: synth-MLP
  group: Spasm
  entity: YOUR_ENTITY_HERE
dataset:
  format: EmJ-Synth-Spasm10
  name: FracDom
  task: graph
  task_type: regression
  transductive: False
  follow_edge_batch: True #set to true when processing edge features in parallel
  node_encoder: True
  node_encoder_name: MLPNodeEnc
  node_encoder_init_dim: 43
  node_encoder_hid_dim: 64
  node_encoder_depths: 2
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: MLPGraphReg
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: mean
mlp:
  layers: 4
  dim_hidden: 145
  residual_connection: True
  batch_norm: True
  dropout: 0.2
  head: san_graph
optim:
  clip_grad_norm: False
  optimizer: adam
  weight_decay: 0.0
  reduce_factor: 0.5
  schedule_patience: 10
  base_lr: 0.001
  max_epoch: 1000
  scheduler: reduce_on_plateau