out_dir: results
metric_best: mae
metric_agg: argmin
seed: 0
wandb:
  use: True
  project: SynthAC_GPS_initial
  group: RWSE
dataset:
  format: EmJ-Synth
  name: AvgClust
  task: graph
  task_type: regression
  transductive: False
  follow_edge_batch: True #set to true when processing edge features in parallel
  node_encoder: True
  node_encoder_name: TypeDictNode+RWSE
  node_encoder_num_types: 1
  node_encoder_bn: False
  edge_encoder: False
posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,21)
  model: mlp_flat
  dim_pe: 28
  raw_norm_type: BatchNorm
  layers: 2
  norm: "batch_norm"
train:
  mode: custom
  batch_size: 128
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: l1
  edge_decoding: dot
  graph_pooling: add
gt:
  layer_type: GIN+Transformer  # CustomGatedGCN+Performer
  layers: 10
  n_heads: 4
  dim_hidden: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.5
  layer_norm: False
  batch_norm: True
gnn:
  head: san_graph
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.001
  max_epoch: 1200
  scheduler: cosine_with_warmup
  num_warmup_epochs: 30